-- Create the generic knowledge_base_v3 table
-- Based on v2 but optimized for Granular RAG Chunking
-- Includes all original columns for migration compatibility + new RAG fields

CREATE TABLE IF NOT EXISTS knowledge_base_v3 (
    -- Primary key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Core RAG Fields (Standard for LangChain/Supabase)
    content TEXT NOT NULL DEFAULT '',
    metadata JSONB DEFAULT '{}'::jsonb,
    embedding vector(1536), 

    -- Chunking & Hierarchy (New in v3)
    chunk_type TEXT NOT NULL DEFAULT 'general', -- 'identity', 'medical', 'composition', 'faq', 'variant'
    parent_doc_id TEXT, -- References the doc_id of the parent/master chunk if applicable
    parent_product_id TEXT, -- References the ID of the base product

    -- Legacy/Compatibility Fields
    doc_id VARCHAR(100) NOT NULL UNIQUE, -- Unique ID for this specific chunk
    success BOOLEAN NOT NULL DEFAULT true,
    error TEXT,
    is_product BOOLEAN NOT NULL DEFAULT false,
    is_product_content BOOLEAN NOT NULL DEFAULT false,
    pagecontent TEXT DEFAULT '', -- Kept for compatibility
    chunk_id INTEGER DEFAULT 0,
    section_index INTEGER DEFAULT 0,
    chunk_length INTEGER DEFAULT 0,
    
    -- Business Fields
    business_domain VARCHAR(50) DEFAULT 'general_business',
    business_subdomain VARCHAR(50) DEFAULT 'general_info',
    key_topics TEXT[] DEFAULT '{}',
    content_categories TEXT[] DEFAULT '{general_business}',
    key_concepts TEXT[] DEFAULT '{}',
    section_context TEXT,
    content_quality VARCHAR(20) DEFAULT 'medium',
    language VARCHAR(10) DEFAULT 'en',
    domain VARCHAR(50) DEFAULT 'business_operations',
    source_type VARCHAR(50) DEFAULT 'company_knowledge_base',

    -- Product Specifics
    product_name VARCHAR(255) DEFAULT '',
    supplier VARCHAR(255) DEFAULT '',
    product_id VARCHAR(50) DEFAULT '',
    price_current VARCHAR(50) DEFAULT '',
    price_original VARCHAR(50) DEFAULT '',
    savings VARCHAR(50) DEFAULT '',
    unit VARCHAR(100) DEFAULT '',
    availability VARCHAR(100) DEFAULT '',
    description TEXT DEFAULT '',
    ingredients TEXT DEFAULT '',
    dosage_instructions TEXT DEFAULT '',
    warnings TEXT DEFAULT '',
    properties TEXT[] DEFAULT '{}',
    
    -- Source Meta
    source_url TEXT DEFAULT '',
    scrape_id VARCHAR(100) DEFAULT '',
    original_filename VARCHAR(255) DEFAULT '',
    original_length INTEGER DEFAULT 0,
    cleaned_length INTEGER DEFAULT 0,
    reduction_percentage DECIMAL(5,2) DEFAULT 0.00,
    content_cleaned BOOLEAN DEFAULT false,
    extracted_fields_count INTEGER DEFAULT 0,
    content_intent VARCHAR(50) DEFAULT 'informational',
    target_audience VARCHAR(50) DEFAULT 'customers',
    content_type VARCHAR(50) DEFAULT 'web_content',
    business_entities TEXT[] DEFAULT '{}',

    -- Timestamps
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for RAG Performance
CREATE INDEX IF NOT EXISTS idx_kb_v3_doc_id ON knowledge_base_v3 (doc_id);
CREATE INDEX IF NOT EXISTS idx_kb_v3_product_id ON knowledge_base_v3 (product_id);
CREATE INDEX IF NOT EXISTS idx_kb_v3_parent_product_id ON knowledge_base_v3 (parent_product_id);
CREATE INDEX IF NOT EXISTS idx_kb_v3_chunk_type ON knowledge_base_v3 (chunk_type);
CREATE INDEX IF NOT EXISTS idx_kb_v3_embedding ON knowledge_base_v3 USING hnsw (embedding vector_cosine_ops);
